general {
    interval = 1
    markup = "pango"
}

order += "disk /"
order += "memory"
order += "battery 0"
order += "volume master"
order += "time"

disk "/" {
    format = "<span foreground='#666666'>D:</span>%percentage_used_of_avail"
}

memory {
    format = "<span foreground='#666666'>M:</span>%percentage_used"
}

battery 0 {
    format = "<span foreground='#666666'>B:</span>%percentage"
    format_down = "<span foreground='#666666'>B:</span>-"
}

volume master {
    format = "<span foreground='#666666'>V:</span>%volume"
}

time {
    format = "%d-%m-%Y %H:%M:%S"
}
